- name: converge
  hosts: all
  become: true
  roles:
    - role: ansible-role-haproxy
      vars:
        haproxy_backend_servers:
          - name: app1
            address: 192.168.0.1
          - name: app2
            address: 192.168.0.2
  post_tasks: []
